# Generated by Django 3.1.7 on 2021-06-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(choices=[('arabe', 'arabe'), ('math', 'math'), ('FR', 'FR')], max_length=25)),
                ('dateDebut', models.DateTimeField()),
                ('dateFin', models.DateTimeField()),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
