# Generated by Django 3.1.7 on 2021-06-21 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Surveillants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('num', models.IntegerField()),
                ('cycle', models.CharField(choices=[('primaire', 'primaire'), ('secondaire', (('collegial', 'collegial'), ('qualifiant', 'qualifiant')))], max_length=15)),
                ('description', models.TextField(max_length=1000)),
                ('published', models.DateTimeField(auto_now=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Surveillants.matiere')),
            ],
        ),
    ]
