# Generated by Django 3.2.4 on 2021-06-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professeurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='matiere',
            field=models.CharField(choices=[('arabe', 'arabe'), ('math', 'math'), ('FR', 'FR')], default='', max_length=25),
            preserve_default=False,
        ),
    ]
