# Generated by Django 3.2.4 on 2021-06-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professeurs', '0002_prof_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='رقم',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prof',
            name='matiere',
            field=models.CharField(choices=[('arabe', 'arabe'), ('math', 'math'), ('FR', 'FR')], default='', max_length=25),
        ),
    ]
