# Generated by Django 3.2.4 on 2021-06-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professeurs', '0003_auto_20210614_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prof',
            old_name='رقم',
            new_name='num',
        ),
        migrations.AddField(
            model_name='prof',
            name='cycle',
            field=models.CharField(choices=[('primaire', 'primaire'), ('secondaire', (('collegial', 'collegial'), ('qualifiant', 'qualifiant')))], default='', max_length=15),
            preserve_default=False,
        ),
    ]
