# Generated by Django 3.2.4 on 2021-06-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professeurs', '0004_auto_20210614_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
