# Generated by Django 3.2.4 on 2021-06-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professeurs', '0005_prof_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='published',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prof',
            name='num',
            field=models.IntegerField(default=1),
        ),
    ]
